### PR TITLE
set `PHABRICATOR_HOST=localhost` in `docker-compose.yml` by default

### PR DESCRIPTION
**Pull request by sameersbn**

### CODE REVIEW

**Comment by chipironcin** [comment]
Wouldnt it be better to use `127.0.0.1`?

**Comment by sameersbn** [comment]
@chipironcin it's the same isn't it?

**Comment by chipironcin** [comment]
mmmm I believe `127.0.0.1` is more standard or supported as is an IP, not a hostname that has to be resolved (plus I have the vague memory of an application not supporting `localhost` but an IP or full domain like `xxxxx.xxx` or an IP, maybe Phabricator)

**Comment by sameersbn** [comment]
you're right.. I didn't realize it but only `127.0.0.1` works with phabricator and the application also needs to be accessed by the same ip. This is specific to phabricator. Do you think we should generalize it and use `127.0.0.1` in place of `localhost` for all applications?

**Pull request merged**
